language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0-preview2-003121

branches:
  only:
  - master

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.4

before_script:
  dotnet restore PerformanceEvaluation.sln

script:
  - dotnet build PerformanceEvaluation.sln
  - dotnet test tests/Services/ScenarioManagement/ScenarioManagement.API.UnitTests/ScenarioManagement.API.UnitTests.csproj
  - dotnet test tests/Services/ScenarioManagement/ScenarioManagement.Domain.UnitTests/ScenarioManagement.Domain.UnitTests.csproj
